version: '3.8'

services:

  backend:
    build: ./backend/
    ports:
      - 5000:5000
    volumes:
      - ./backend/mtdgui:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  frontend:
    build: ./frontend
    volumes:
      - './frontend/CITS3200 - MTD Simulator:/app
      - '/app/node_modules'
    ports:
      - 8080:8080